### PR TITLE
Try to build for Linux ARM

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Review by grondo — APPROVED** [review]
This looks fine to me, and we do run and test flux-core on aarch64 regularly, so I don't expect any problems. Was there something specific you wanted me to look at @jan-janssen?

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@grondo I guess we still have the version updates https://github.com/conda-forge/flux-core-feedstock/pull/48 - which are missing on conda. Would you have time to take a look at those?

**Comment by jan-janssen** [comment]
@grondo In terms of this pull request - I think conda is always automatically adding the code owners of the recipe for review. So it was an automated action, rather than me requesting the review personally.

**Comment by grondo** [comment]
Ah, that makes sense. Thanks!

**Pull request merged**
