### PR TITLE
Add pyyaml to dependencies

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@grondo During testing flux we noticed that these dependencies have to be added otherwise flux fails with rather cryptic error messages.

**Comment by grondo** [comment]
Ah, yes, sorry this is listed in the requirements [here](https://github.com/flux-framework/flux-core/blob/master/scripts/install-deps-deb.sh). I had forgotten it.

**Comment by jan-janssen** [comment]
It is fine - we had them in `host` but I forgot to add them to `run` as I was not sure which of these packages is a python package. Nevertheless with these fixes we are now able to use `flux` on our internal HPC systems, at least on the user-level.

**Pull request merged**
