### PR TITLE
Add run_exports

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
The run_exports feature can be used to specify the versions that are ABI compatible with the built version. Here I assume that 0.49.0 is ABI compatible to 0.49.X and so on. https://conda-forge.org/docs/maintainer/pinning_deps.html#specifying-run-exports

**Comment by grondo** [comment]
>  Here I assume that 0.49.0 is ABI compatible to 0.49.X and so on

In practice we have much better ABI compatibility than that (meaning a program compiled against an older libflux-core will usually work with a newer version), however, flux-core exports a very large C and Python API so your choice here may be safest.

**Review by grondo — COMMENTED** [review]
LGTM, though it doesn't appear I can technically approve.

**Pull request merged**
